// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 319.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'zombies';

  static const String assets_Fireball1_png = 'assets/Fireball1.png';
  static const String zombies$assets_Fireball1_png = 'packages/zombies/assets/Fireball1.png';

  static const String assets_characters_Adventurer_Poses_adventurer_action1_png = 'assets/characters/Adventurer/Poses/adventurer_action1.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_action1_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_action1.png';

  static const String assets_characters_Adventurer_Poses_adventurer_action2_png = 'assets/characters/Adventurer/Poses/adventurer_action2.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_action2_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_action2.png';

  static const String assets_characters_Adventurer_Poses_adventurer_back_png = 'assets/characters/Adventurer/Poses/adventurer_back.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_back_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_back.png';

  static const String assets_characters_Adventurer_Poses_adventurer_cheer1_png = 'assets/characters/Adventurer/Poses/adventurer_cheer1.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_cheer1_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_cheer1.png';

  static const String assets_characters_Adventurer_Poses_adventurer_cheer2_png = 'assets/characters/Adventurer/Poses/adventurer_cheer2.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_cheer2_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_cheer2.png';

  static const String assets_characters_Adventurer_Poses_adventurer_climb1_png = 'assets/characters/Adventurer/Poses/adventurer_climb1.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_climb1_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_climb1.png';

  static const String assets_characters_Adventurer_Poses_adventurer_climb2_png = 'assets/characters/Adventurer/Poses/adventurer_climb2.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_climb2_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_climb2.png';

  static const String assets_characters_Adventurer_Poses_adventurer_duck_png = 'assets/characters/Adventurer/Poses/adventurer_duck.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_duck_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_duck.png';

  static const String assets_characters_Adventurer_Poses_adventurer_fall_png = 'assets/characters/Adventurer/Poses/adventurer_fall.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_fall_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_fall.png';

  static const String assets_characters_Adventurer_Poses_adventurer_hang_png = 'assets/characters/Adventurer/Poses/adventurer_hang.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_hang_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_hang.png';

  static const String assets_characters_Adventurer_Poses_adventurer_hold1_png = 'assets/characters/Adventurer/Poses/adventurer_hold1.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_hold1_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_hold1.png';

  static const String assets_characters_Adventurer_Poses_adventurer_hold2_png = 'assets/characters/Adventurer/Poses/adventurer_hold2.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_hold2_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_hold2.png';

  static const String assets_characters_Adventurer_Poses_adventurer_hurt_png = 'assets/characters/Adventurer/Poses/adventurer_hurt.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_hurt_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_hurt.png';

  static const String assets_characters_Adventurer_Poses_adventurer_idle_png = 'assets/characters/Adventurer/Poses/adventurer_idle.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_idle_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_idle.png';

  static const String assets_characters_Adventurer_Poses_adventurer_jump_png = 'assets/characters/Adventurer/Poses/adventurer_jump.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_jump_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_jump.png';

  static const String assets_characters_Adventurer_Poses_adventurer_kick_png = 'assets/characters/Adventurer/Poses/adventurer_kick.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_kick_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_kick.png';

  static const String assets_characters_Adventurer_Poses_adventurer_skid_png = 'assets/characters/Adventurer/Poses/adventurer_skid.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_skid_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_skid.png';

  static const String assets_characters_Adventurer_Poses_adventurer_slide_png = 'assets/characters/Adventurer/Poses/adventurer_slide.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_slide_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_slide.png';

  static const String assets_characters_Adventurer_Poses_adventurer_stand_png = 'assets/characters/Adventurer/Poses/adventurer_stand.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_stand_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_stand.png';

  static const String assets_characters_Adventurer_Poses_adventurer_swim1_png = 'assets/characters/Adventurer/Poses/adventurer_swim1.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_swim1_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_swim1.png';

  static const String assets_characters_Adventurer_Poses_adventurer_swim2_png = 'assets/characters/Adventurer/Poses/adventurer_swim2.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_swim2_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_swim2.png';

  static const String assets_characters_Adventurer_Poses_adventurer_talk_png = 'assets/characters/Adventurer/Poses/adventurer_talk.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_talk_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_talk.png';

  static const String assets_characters_Adventurer_Poses_adventurer_walk1_png = 'assets/characters/Adventurer/Poses/adventurer_walk1.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_walk1_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_walk1.png';

  static const String assets_characters_Adventurer_Poses_adventurer_walk2_png = 'assets/characters/Adventurer/Poses/adventurer_walk2.png';
  static const String zombies$assets_characters_Adventurer_Poses_adventurer_walk2_png = 'packages/zombies/assets/characters/Adventurer/Poses/adventurer_walk2.png';

  static const String assets_characters_Zombie_Poses_zombie_action1_png = 'assets/characters/Zombie/Poses/zombie_action1.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_action1_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_action1.png';

  static const String assets_characters_Zombie_Poses_zombie_action2_png = 'assets/characters/Zombie/Poses/zombie_action2.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_action2_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_action2.png';

  static const String assets_characters_Zombie_Poses_zombie_back_png = 'assets/characters/Zombie/Poses/zombie_back.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_back_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_back.png';

  static const String assets_characters_Zombie_Poses_zombie_cheer1_png = 'assets/characters/Zombie/Poses/zombie_cheer1.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_cheer1_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_cheer1.png';

  static const String assets_characters_Zombie_Poses_zombie_cheer2_png = 'assets/characters/Zombie/Poses/zombie_cheer2.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_cheer2_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_cheer2.png';

  static const String assets_characters_Zombie_Poses_zombie_climb1_png = 'assets/characters/Zombie/Poses/zombie_climb1.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_climb1_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_climb1.png';

  static const String assets_characters_Zombie_Poses_zombie_climb2_png = 'assets/characters/Zombie/Poses/zombie_climb2.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_climb2_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_climb2.png';

  static const String assets_characters_Zombie_Poses_zombie_duck_png = 'assets/characters/Zombie/Poses/zombie_duck.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_duck_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_duck.png';

  static const String assets_characters_Zombie_Poses_zombie_fall_png = 'assets/characters/Zombie/Poses/zombie_fall.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_fall_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_fall.png';

  static const String assets_characters_Zombie_Poses_zombie_hang_png = 'assets/characters/Zombie/Poses/zombie_hang.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_hang_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_hang.png';

  static const String assets_characters_Zombie_Poses_zombie_hold1_png = 'assets/characters/Zombie/Poses/zombie_hold1.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_hold1_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_hold1.png';

  static const String assets_characters_Zombie_Poses_zombie_hold2_png = 'assets/characters/Zombie/Poses/zombie_hold2.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_hold2_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_hold2.png';

  static const String assets_characters_Zombie_Poses_zombie_hurt_png = 'assets/characters/Zombie/Poses/zombie_hurt.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_hurt_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_hurt.png';

  static const String assets_characters_Zombie_Poses_zombie_idle_png = 'assets/characters/Zombie/Poses/zombie_idle.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_idle_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_idle.png';

  static const String assets_characters_Zombie_Poses_zombie_jump_png = 'assets/characters/Zombie/Poses/zombie_jump.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_jump_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_jump.png';

  static const String assets_characters_Zombie_Poses_zombie_kick_png = 'assets/characters/Zombie/Poses/zombie_kick.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_kick_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_kick.png';

  static const String assets_characters_Zombie_Poses_zombie_skid_png = 'assets/characters/Zombie/Poses/zombie_skid.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_skid_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_skid.png';

  static const String assets_characters_Zombie_Poses_zombie_slide_png = 'assets/characters/Zombie/Poses/zombie_slide.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_slide_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_slide.png';

  static const String assets_characters_Zombie_Poses_zombie_stand_png = 'assets/characters/Zombie/Poses/zombie_stand.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_stand_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_stand.png';

  static const String assets_characters_Zombie_Poses_zombie_swim1_png = 'assets/characters/Zombie/Poses/zombie_swim1.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_swim1_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_swim1.png';

  static const String assets_characters_Zombie_Poses_zombie_swim2_png = 'assets/characters/Zombie/Poses/zombie_swim2.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_swim2_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_swim2.png';

  static const String assets_characters_Zombie_Poses_zombie_talk_png = 'assets/characters/Zombie/Poses/zombie_talk.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_talk_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_talk.png';

  static const String assets_characters_Zombie_Poses_zombie_walk1_png = 'assets/characters/Zombie/Poses/zombie_walk1.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_walk1_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_walk1.png';

  static const String assets_characters_Zombie_Poses_zombie_walk2_png = 'assets/characters/Zombie/Poses/zombie_walk2.png';
  static const String zombies$assets_characters_Zombie_Poses_zombie_walk2_png = 'packages/zombies/assets/characters/Zombie/Poses/zombie_walk2.png';

  static const String assets_dungeon_tile_0000_png = 'assets/dungeon/tile_0000.png';
  static const String zombies$assets_dungeon_tile_0000_png = 'packages/zombies/assets/dungeon/tile_0000.png';

  static const String assets_dungeon_tile_0001_png = 'assets/dungeon/tile_0001.png';
  static const String zombies$assets_dungeon_tile_0001_png = 'packages/zombies/assets/dungeon/tile_0001.png';

  static const String assets_dungeon_tile_0002_png = 'assets/dungeon/tile_0002.png';
  static const String zombies$assets_dungeon_tile_0002_png = 'packages/zombies/assets/dungeon/tile_0002.png';

  static const String assets_dungeon_tile_0003_png = 'assets/dungeon/tile_0003.png';
  static const String zombies$assets_dungeon_tile_0003_png = 'packages/zombies/assets/dungeon/tile_0003.png';

  static const String assets_dungeon_tile_0004_png = 'assets/dungeon/tile_0004.png';
  static const String zombies$assets_dungeon_tile_0004_png = 'packages/zombies/assets/dungeon/tile_0004.png';

  static const String assets_dungeon_tile_0005_png = 'assets/dungeon/tile_0005.png';
  static const String zombies$assets_dungeon_tile_0005_png = 'packages/zombies/assets/dungeon/tile_0005.png';

  static const String assets_dungeon_tile_0006_png = 'assets/dungeon/tile_0006.png';
  static const String zombies$assets_dungeon_tile_0006_png = 'packages/zombies/assets/dungeon/tile_0006.png';

  static const String assets_dungeon_tile_0007_png = 'assets/dungeon/tile_0007.png';
  static const String zombies$assets_dungeon_tile_0007_png = 'packages/zombies/assets/dungeon/tile_0007.png';

  static const String assets_dungeon_tile_0008_png = 'assets/dungeon/tile_0008.png';
  static const String zombies$assets_dungeon_tile_0008_png = 'packages/zombies/assets/dungeon/tile_0008.png';

  static const String assets_dungeon_tile_0009_png = 'assets/dungeon/tile_0009.png';
  static const String zombies$assets_dungeon_tile_0009_png = 'packages/zombies/assets/dungeon/tile_0009.png';

  static const String assets_dungeon_tile_0010_png = 'assets/dungeon/tile_0010.png';
  static const String zombies$assets_dungeon_tile_0010_png = 'packages/zombies/assets/dungeon/tile_0010.png';

  static const String assets_dungeon_tile_0011_png = 'assets/dungeon/tile_0011.png';
  static const String zombies$assets_dungeon_tile_0011_png = 'packages/zombies/assets/dungeon/tile_0011.png';

  static const String assets_dungeon_tile_0012_png = 'assets/dungeon/tile_0012.png';
  static const String zombies$assets_dungeon_tile_0012_png = 'packages/zombies/assets/dungeon/tile_0012.png';

  static const String assets_dungeon_tile_0013_png = 'assets/dungeon/tile_0013.png';
  static const String zombies$assets_dungeon_tile_0013_png = 'packages/zombies/assets/dungeon/tile_0013.png';

  static const String assets_dungeon_tile_0014_png = 'assets/dungeon/tile_0014.png';
  static const String zombies$assets_dungeon_tile_0014_png = 'packages/zombies/assets/dungeon/tile_0014.png';

  static const String assets_dungeon_tile_0015_png = 'assets/dungeon/tile_0015.png';
  static const String zombies$assets_dungeon_tile_0015_png = 'packages/zombies/assets/dungeon/tile_0015.png';

  static const String assets_dungeon_tile_0016_png = 'assets/dungeon/tile_0016.png';
  static const String zombies$assets_dungeon_tile_0016_png = 'packages/zombies/assets/dungeon/tile_0016.png';

  static const String assets_dungeon_tile_0017_png = 'assets/dungeon/tile_0017.png';
  static const String zombies$assets_dungeon_tile_0017_png = 'packages/zombies/assets/dungeon/tile_0017.png';

  static const String assets_dungeon_tile_0018_png = 'assets/dungeon/tile_0018.png';
  static const String zombies$assets_dungeon_tile_0018_png = 'packages/zombies/assets/dungeon/tile_0018.png';

  static const String assets_dungeon_tile_0019_png = 'assets/dungeon/tile_0019.png';
  static const String zombies$assets_dungeon_tile_0019_png = 'packages/zombies/assets/dungeon/tile_0019.png';

  static const String assets_dungeon_tile_0020_png = 'assets/dungeon/tile_0020.png';
  static const String zombies$assets_dungeon_tile_0020_png = 'packages/zombies/assets/dungeon/tile_0020.png';

  static const String assets_dungeon_tile_0021_png = 'assets/dungeon/tile_0021.png';
  static const String zombies$assets_dungeon_tile_0021_png = 'packages/zombies/assets/dungeon/tile_0021.png';

  static const String assets_dungeon_tile_0022_png = 'assets/dungeon/tile_0022.png';
  static const String zombies$assets_dungeon_tile_0022_png = 'packages/zombies/assets/dungeon/tile_0022.png';

  static const String assets_dungeon_tile_0023_png = 'assets/dungeon/tile_0023.png';
  static const String zombies$assets_dungeon_tile_0023_png = 'packages/zombies/assets/dungeon/tile_0023.png';

  static const String assets_dungeon_tile_0024_png = 'assets/dungeon/tile_0024.png';
  static const String zombies$assets_dungeon_tile_0024_png = 'packages/zombies/assets/dungeon/tile_0024.png';

  static const String assets_dungeon_tile_0025_png = 'assets/dungeon/tile_0025.png';
  static const String zombies$assets_dungeon_tile_0025_png = 'packages/zombies/assets/dungeon/tile_0025.png';

  static const String assets_dungeon_tile_0026_png = 'assets/dungeon/tile_0026.png';
  static const String zombies$assets_dungeon_tile_0026_png = 'packages/zombies/assets/dungeon/tile_0026.png';

  static const String assets_dungeon_tile_0027_png = 'assets/dungeon/tile_0027.png';
  static const String zombies$assets_dungeon_tile_0027_png = 'packages/zombies/assets/dungeon/tile_0027.png';

  static const String assets_dungeon_tile_0028_png = 'assets/dungeon/tile_0028.png';
  static const String zombies$assets_dungeon_tile_0028_png = 'packages/zombies/assets/dungeon/tile_0028.png';

  static const String assets_dungeon_tile_0029_png = 'assets/dungeon/tile_0029.png';
  static const String zombies$assets_dungeon_tile_0029_png = 'packages/zombies/assets/dungeon/tile_0029.png';

  static const String assets_dungeon_tile_0030_png = 'assets/dungeon/tile_0030.png';
  static const String zombies$assets_dungeon_tile_0030_png = 'packages/zombies/assets/dungeon/tile_0030.png';

  static const String assets_dungeon_tile_0031_png = 'assets/dungeon/tile_0031.png';
  static const String zombies$assets_dungeon_tile_0031_png = 'packages/zombies/assets/dungeon/tile_0031.png';

  static const String assets_dungeon_tile_0032_png = 'assets/dungeon/tile_0032.png';
  static const String zombies$assets_dungeon_tile_0032_png = 'packages/zombies/assets/dungeon/tile_0032.png';

  static const String assets_dungeon_tile_0033_png = 'assets/dungeon/tile_0033.png';
  static const String zombies$assets_dungeon_tile_0033_png = 'packages/zombies/assets/dungeon/tile_0033.png';

  static const String assets_dungeon_tile_0034_png = 'assets/dungeon/tile_0034.png';
  static const String zombies$assets_dungeon_tile_0034_png = 'packages/zombies/assets/dungeon/tile_0034.png';

  static const String assets_dungeon_tile_0035_png = 'assets/dungeon/tile_0035.png';
  static const String zombies$assets_dungeon_tile_0035_png = 'packages/zombies/assets/dungeon/tile_0035.png';

  static const String assets_dungeon_tile_0036_png = 'assets/dungeon/tile_0036.png';
  static const String zombies$assets_dungeon_tile_0036_png = 'packages/zombies/assets/dungeon/tile_0036.png';

  static const String assets_dungeon_tile_0037_png = 'assets/dungeon/tile_0037.png';
  static const String zombies$assets_dungeon_tile_0037_png = 'packages/zombies/assets/dungeon/tile_0037.png';

  static const String assets_dungeon_tile_0038_png = 'assets/dungeon/tile_0038.png';
  static const String zombies$assets_dungeon_tile_0038_png = 'packages/zombies/assets/dungeon/tile_0038.png';

  static const String assets_dungeon_tile_0039_png = 'assets/dungeon/tile_0039.png';
  static const String zombies$assets_dungeon_tile_0039_png = 'packages/zombies/assets/dungeon/tile_0039.png';

  static const String assets_dungeon_tile_0040_png = 'assets/dungeon/tile_0040.png';
  static const String zombies$assets_dungeon_tile_0040_png = 'packages/zombies/assets/dungeon/tile_0040.png';

  static const String assets_dungeon_tile_0041_png = 'assets/dungeon/tile_0041.png';
  static const String zombies$assets_dungeon_tile_0041_png = 'packages/zombies/assets/dungeon/tile_0041.png';

  static const String assets_dungeon_tile_0042_png = 'assets/dungeon/tile_0042.png';
  static const String zombies$assets_dungeon_tile_0042_png = 'packages/zombies/assets/dungeon/tile_0042.png';

  static const String assets_dungeon_tile_0043_png = 'assets/dungeon/tile_0043.png';
  static const String zombies$assets_dungeon_tile_0043_png = 'packages/zombies/assets/dungeon/tile_0043.png';

  static const String assets_dungeon_tile_0044_png = 'assets/dungeon/tile_0044.png';
  static const String zombies$assets_dungeon_tile_0044_png = 'packages/zombies/assets/dungeon/tile_0044.png';

  static const String assets_dungeon_tile_0045_png = 'assets/dungeon/tile_0045.png';
  static const String zombies$assets_dungeon_tile_0045_png = 'packages/zombies/assets/dungeon/tile_0045.png';

  static const String assets_dungeon_tile_0046_png = 'assets/dungeon/tile_0046.png';
  static const String zombies$assets_dungeon_tile_0046_png = 'packages/zombies/assets/dungeon/tile_0046.png';

  static const String assets_dungeon_tile_0047_png = 'assets/dungeon/tile_0047.png';
  static const String zombies$assets_dungeon_tile_0047_png = 'packages/zombies/assets/dungeon/tile_0047.png';

  static const String assets_dungeon_tile_0048_png = 'assets/dungeon/tile_0048.png';
  static const String zombies$assets_dungeon_tile_0048_png = 'packages/zombies/assets/dungeon/tile_0048.png';

  static const String assets_dungeon_tile_0049_png = 'assets/dungeon/tile_0049.png';
  static const String zombies$assets_dungeon_tile_0049_png = 'packages/zombies/assets/dungeon/tile_0049.png';

  static const String assets_dungeon_tile_0050_png = 'assets/dungeon/tile_0050.png';
  static const String zombies$assets_dungeon_tile_0050_png = 'packages/zombies/assets/dungeon/tile_0050.png';

  static const String assets_dungeon_tile_0051_png = 'assets/dungeon/tile_0051.png';
  static const String zombies$assets_dungeon_tile_0051_png = 'packages/zombies/assets/dungeon/tile_0051.png';

  static const String assets_dungeon_tile_0052_png = 'assets/dungeon/tile_0052.png';
  static const String zombies$assets_dungeon_tile_0052_png = 'packages/zombies/assets/dungeon/tile_0052.png';

  static const String assets_dungeon_tile_0053_png = 'assets/dungeon/tile_0053.png';
  static const String zombies$assets_dungeon_tile_0053_png = 'packages/zombies/assets/dungeon/tile_0053.png';

  static const String assets_dungeon_tile_0054_png = 'assets/dungeon/tile_0054.png';
  static const String zombies$assets_dungeon_tile_0054_png = 'packages/zombies/assets/dungeon/tile_0054.png';

  static const String assets_dungeon_tile_0055_png = 'assets/dungeon/tile_0055.png';
  static const String zombies$assets_dungeon_tile_0055_png = 'packages/zombies/assets/dungeon/tile_0055.png';

  static const String assets_dungeon_tile_0056_png = 'assets/dungeon/tile_0056.png';
  static const String zombies$assets_dungeon_tile_0056_png = 'packages/zombies/assets/dungeon/tile_0056.png';

  static const String assets_dungeon_tile_0057_png = 'assets/dungeon/tile_0057.png';
  static const String zombies$assets_dungeon_tile_0057_png = 'packages/zombies/assets/dungeon/tile_0057.png';

  static const String assets_dungeon_tile_0058_png = 'assets/dungeon/tile_0058.png';
  static const String zombies$assets_dungeon_tile_0058_png = 'packages/zombies/assets/dungeon/tile_0058.png';

  static const String assets_dungeon_tile_0059_png = 'assets/dungeon/tile_0059.png';
  static const String zombies$assets_dungeon_tile_0059_png = 'packages/zombies/assets/dungeon/tile_0059.png';

  static const String assets_dungeon_tile_0060_png = 'assets/dungeon/tile_0060.png';
  static const String zombies$assets_dungeon_tile_0060_png = 'packages/zombies/assets/dungeon/tile_0060.png';

  static const String assets_dungeon_tile_0061_png = 'assets/dungeon/tile_0061.png';
  static const String zombies$assets_dungeon_tile_0061_png = 'packages/zombies/assets/dungeon/tile_0061.png';

  static const String assets_dungeon_tile_0062_png = 'assets/dungeon/tile_0062.png';
  static const String zombies$assets_dungeon_tile_0062_png = 'packages/zombies/assets/dungeon/tile_0062.png';

  static const String assets_dungeon_tile_0063_png = 'assets/dungeon/tile_0063.png';
  static const String zombies$assets_dungeon_tile_0063_png = 'packages/zombies/assets/dungeon/tile_0063.png';

  static const String assets_dungeon_tile_0064_png = 'assets/dungeon/tile_0064.png';
  static const String zombies$assets_dungeon_tile_0064_png = 'packages/zombies/assets/dungeon/tile_0064.png';

  static const String assets_dungeon_tile_0065_png = 'assets/dungeon/tile_0065.png';
  static const String zombies$assets_dungeon_tile_0065_png = 'packages/zombies/assets/dungeon/tile_0065.png';

  static const String assets_dungeon_tile_0066_png = 'assets/dungeon/tile_0066.png';
  static const String zombies$assets_dungeon_tile_0066_png = 'packages/zombies/assets/dungeon/tile_0066.png';

  static const String assets_dungeon_tile_0067_png = 'assets/dungeon/tile_0067.png';
  static const String zombies$assets_dungeon_tile_0067_png = 'packages/zombies/assets/dungeon/tile_0067.png';

  static const String assets_dungeon_tile_0068_png = 'assets/dungeon/tile_0068.png';
  static const String zombies$assets_dungeon_tile_0068_png = 'packages/zombies/assets/dungeon/tile_0068.png';

  static const String assets_dungeon_tile_0069_png = 'assets/dungeon/tile_0069.png';
  static const String zombies$assets_dungeon_tile_0069_png = 'packages/zombies/assets/dungeon/tile_0069.png';

  static const String assets_dungeon_tile_0070_png = 'assets/dungeon/tile_0070.png';
  static const String zombies$assets_dungeon_tile_0070_png = 'packages/zombies/assets/dungeon/tile_0070.png';

  static const String assets_dungeon_tile_0071_png = 'assets/dungeon/tile_0071.png';
  static const String zombies$assets_dungeon_tile_0071_png = 'packages/zombies/assets/dungeon/tile_0071.png';

  static const String assets_dungeon_tile_0072_png = 'assets/dungeon/tile_0072.png';
  static const String zombies$assets_dungeon_tile_0072_png = 'packages/zombies/assets/dungeon/tile_0072.png';

  static const String assets_dungeon_tile_0073_png = 'assets/dungeon/tile_0073.png';
  static const String zombies$assets_dungeon_tile_0073_png = 'packages/zombies/assets/dungeon/tile_0073.png';

  static const String assets_dungeon_tile_0074_png = 'assets/dungeon/tile_0074.png';
  static const String zombies$assets_dungeon_tile_0074_png = 'packages/zombies/assets/dungeon/tile_0074.png';

  static const String assets_dungeon_tile_0075_png = 'assets/dungeon/tile_0075.png';
  static const String zombies$assets_dungeon_tile_0075_png = 'packages/zombies/assets/dungeon/tile_0075.png';

  static const String assets_dungeon_tile_0076_png = 'assets/dungeon/tile_0076.png';
  static const String zombies$assets_dungeon_tile_0076_png = 'packages/zombies/assets/dungeon/tile_0076.png';

  static const String assets_dungeon_tile_0077_png = 'assets/dungeon/tile_0077.png';
  static const String zombies$assets_dungeon_tile_0077_png = 'packages/zombies/assets/dungeon/tile_0077.png';

  static const String assets_dungeon_tile_0078_png = 'assets/dungeon/tile_0078.png';
  static const String zombies$assets_dungeon_tile_0078_png = 'packages/zombies/assets/dungeon/tile_0078.png';

  static const String assets_dungeon_tile_0079_png = 'assets/dungeon/tile_0079.png';
  static const String zombies$assets_dungeon_tile_0079_png = 'packages/zombies/assets/dungeon/tile_0079.png';

  static const String assets_dungeon_tile_0080_png = 'assets/dungeon/tile_0080.png';
  static const String zombies$assets_dungeon_tile_0080_png = 'packages/zombies/assets/dungeon/tile_0080.png';

  static const String assets_dungeon_tile_0081_png = 'assets/dungeon/tile_0081.png';
  static const String zombies$assets_dungeon_tile_0081_png = 'packages/zombies/assets/dungeon/tile_0081.png';

  static const String assets_dungeon_tile_0082_png = 'assets/dungeon/tile_0082.png';
  static const String zombies$assets_dungeon_tile_0082_png = 'packages/zombies/assets/dungeon/tile_0082.png';

  static const String assets_dungeon_tile_0083_png = 'assets/dungeon/tile_0083.png';
  static const String zombies$assets_dungeon_tile_0083_png = 'packages/zombies/assets/dungeon/tile_0083.png';

  static const String assets_dungeon_tile_0084_png = 'assets/dungeon/tile_0084.png';
  static const String zombies$assets_dungeon_tile_0084_png = 'packages/zombies/assets/dungeon/tile_0084.png';

  static const String assets_dungeon_tile_0085_png = 'assets/dungeon/tile_0085.png';
  static const String zombies$assets_dungeon_tile_0085_png = 'packages/zombies/assets/dungeon/tile_0085.png';

  static const String assets_dungeon_tile_0086_png = 'assets/dungeon/tile_0086.png';
  static const String zombies$assets_dungeon_tile_0086_png = 'packages/zombies/assets/dungeon/tile_0086.png';

  static const String assets_dungeon_tile_0087_png = 'assets/dungeon/tile_0087.png';
  static const String zombies$assets_dungeon_tile_0087_png = 'packages/zombies/assets/dungeon/tile_0087.png';

  static const String assets_dungeon_tile_0088_png = 'assets/dungeon/tile_0088.png';
  static const String zombies$assets_dungeon_tile_0088_png = 'packages/zombies/assets/dungeon/tile_0088.png';

  static const String assets_dungeon_tile_0089_png = 'assets/dungeon/tile_0089.png';
  static const String zombies$assets_dungeon_tile_0089_png = 'packages/zombies/assets/dungeon/tile_0089.png';

  static const String assets_dungeon_tile_0090_png = 'assets/dungeon/tile_0090.png';
  static const String zombies$assets_dungeon_tile_0090_png = 'packages/zombies/assets/dungeon/tile_0090.png';

  static const String assets_dungeon_tile_0091_png = 'assets/dungeon/tile_0091.png';
  static const String zombies$assets_dungeon_tile_0091_png = 'packages/zombies/assets/dungeon/tile_0091.png';

  static const String assets_dungeon_tile_0092_png = 'assets/dungeon/tile_0092.png';
  static const String zombies$assets_dungeon_tile_0092_png = 'packages/zombies/assets/dungeon/tile_0092.png';

  static const String assets_dungeon_tile_0093_png = 'assets/dungeon/tile_0093.png';
  static const String zombies$assets_dungeon_tile_0093_png = 'packages/zombies/assets/dungeon/tile_0093.png';

  static const String assets_dungeon_tile_0094_png = 'assets/dungeon/tile_0094.png';
  static const String zombies$assets_dungeon_tile_0094_png = 'packages/zombies/assets/dungeon/tile_0094.png';

  static const String assets_dungeon_tile_0095_png = 'assets/dungeon/tile_0095.png';
  static const String zombies$assets_dungeon_tile_0095_png = 'packages/zombies/assets/dungeon/tile_0095.png';

  static const String assets_dungeon_tile_0096_png = 'assets/dungeon/tile_0096.png';
  static const String zombies$assets_dungeon_tile_0096_png = 'packages/zombies/assets/dungeon/tile_0096.png';

  static const String assets_dungeon_tile_0097_png = 'assets/dungeon/tile_0097.png';
  static const String zombies$assets_dungeon_tile_0097_png = 'packages/zombies/assets/dungeon/tile_0097.png';

  static const String assets_dungeon_tile_0098_png = 'assets/dungeon/tile_0098.png';
  static const String zombies$assets_dungeon_tile_0098_png = 'packages/zombies/assets/dungeon/tile_0098.png';

  static const String assets_dungeon_tile_0099_png = 'assets/dungeon/tile_0099.png';
  static const String zombies$assets_dungeon_tile_0099_png = 'packages/zombies/assets/dungeon/tile_0099.png';

  static const String assets_dungeon_tile_0100_png = 'assets/dungeon/tile_0100.png';
  static const String zombies$assets_dungeon_tile_0100_png = 'packages/zombies/assets/dungeon/tile_0100.png';

  static const String assets_dungeon_tile_0101_png = 'assets/dungeon/tile_0101.png';
  static const String zombies$assets_dungeon_tile_0101_png = 'packages/zombies/assets/dungeon/tile_0101.png';

  static const String assets_dungeon_tile_0102_png = 'assets/dungeon/tile_0102.png';
  static const String zombies$assets_dungeon_tile_0102_png = 'packages/zombies/assets/dungeon/tile_0102.png';

  static const String assets_dungeon_tile_0103_png = 'assets/dungeon/tile_0103.png';
  static const String zombies$assets_dungeon_tile_0103_png = 'packages/zombies/assets/dungeon/tile_0103.png';

  static const String assets_dungeon_tile_0104_png = 'assets/dungeon/tile_0104.png';
  static const String zombies$assets_dungeon_tile_0104_png = 'packages/zombies/assets/dungeon/tile_0104.png';

  static const String assets_dungeon_tile_0105_png = 'assets/dungeon/tile_0105.png';
  static const String zombies$assets_dungeon_tile_0105_png = 'packages/zombies/assets/dungeon/tile_0105.png';

  static const String assets_dungeon_tile_0106_png = 'assets/dungeon/tile_0106.png';
  static const String zombies$assets_dungeon_tile_0106_png = 'packages/zombies/assets/dungeon/tile_0106.png';

  static const String assets_dungeon_tile_0107_png = 'assets/dungeon/tile_0107.png';
  static const String zombies$assets_dungeon_tile_0107_png = 'packages/zombies/assets/dungeon/tile_0107.png';

  static const String assets_dungeon_tile_0108_png = 'assets/dungeon/tile_0108.png';
  static const String zombies$assets_dungeon_tile_0108_png = 'packages/zombies/assets/dungeon/tile_0108.png';

  static const String assets_dungeon_tile_0109_png = 'assets/dungeon/tile_0109.png';
  static const String zombies$assets_dungeon_tile_0109_png = 'packages/zombies/assets/dungeon/tile_0109.png';

  static const String assets_dungeon_tile_0110_png = 'assets/dungeon/tile_0110.png';
  static const String zombies$assets_dungeon_tile_0110_png = 'packages/zombies/assets/dungeon/tile_0110.png';

  static const String assets_dungeon_tile_0111_png = 'assets/dungeon/tile_0111.png';
  static const String zombies$assets_dungeon_tile_0111_png = 'packages/zombies/assets/dungeon/tile_0111.png';

  static const String assets_dungeon_tile_0112_png = 'assets/dungeon/tile_0112.png';
  static const String zombies$assets_dungeon_tile_0112_png = 'packages/zombies/assets/dungeon/tile_0112.png';

  static const String assets_dungeon_tile_0113_png = 'assets/dungeon/tile_0113.png';
  static const String zombies$assets_dungeon_tile_0113_png = 'packages/zombies/assets/dungeon/tile_0113.png';

  static const String assets_dungeon_tile_0114_png = 'assets/dungeon/tile_0114.png';
  static const String zombies$assets_dungeon_tile_0114_png = 'packages/zombies/assets/dungeon/tile_0114.png';

  static const String assets_dungeon_tile_0115_png = 'assets/dungeon/tile_0115.png';
  static const String zombies$assets_dungeon_tile_0115_png = 'packages/zombies/assets/dungeon/tile_0115.png';

  static const String assets_dungeon_tile_0116_png = 'assets/dungeon/tile_0116.png';
  static const String zombies$assets_dungeon_tile_0116_png = 'packages/zombies/assets/dungeon/tile_0116.png';

  static const String assets_dungeon_tile_0117_png = 'assets/dungeon/tile_0117.png';
  static const String zombies$assets_dungeon_tile_0117_png = 'packages/zombies/assets/dungeon/tile_0117.png';

  static const String assets_dungeon_tile_0118_png = 'assets/dungeon/tile_0118.png';
  static const String zombies$assets_dungeon_tile_0118_png = 'packages/zombies/assets/dungeon/tile_0118.png';

  static const String assets_dungeon_tile_0119_png = 'assets/dungeon/tile_0119.png';
  static const String zombies$assets_dungeon_tile_0119_png = 'packages/zombies/assets/dungeon/tile_0119.png';

  static const String assets_dungeon_tile_0120_png = 'assets/dungeon/tile_0120.png';
  static const String zombies$assets_dungeon_tile_0120_png = 'packages/zombies/assets/dungeon/tile_0120.png';

  static const String assets_dungeon_tile_0121_png = 'assets/dungeon/tile_0121.png';
  static const String zombies$assets_dungeon_tile_0121_png = 'packages/zombies/assets/dungeon/tile_0121.png';

  static const String assets_dungeon_tile_0122_png = 'assets/dungeon/tile_0122.png';
  static const String zombies$assets_dungeon_tile_0122_png = 'packages/zombies/assets/dungeon/tile_0122.png';

  static const String assets_dungeon_tile_0123_png = 'assets/dungeon/tile_0123.png';
  static const String zombies$assets_dungeon_tile_0123_png = 'packages/zombies/assets/dungeon/tile_0123.png';

  static const String assets_dungeon_tile_0124_png = 'assets/dungeon/tile_0124.png';
  static const String zombies$assets_dungeon_tile_0124_png = 'packages/zombies/assets/dungeon/tile_0124.png';

  static const String assets_dungeon_tile_0125_png = 'assets/dungeon/tile_0125.png';
  static const String zombies$assets_dungeon_tile_0125_png = 'packages/zombies/assets/dungeon/tile_0125.png';

  static const String assets_dungeon_tile_0126_png = 'assets/dungeon/tile_0126.png';
  static const String zombies$assets_dungeon_tile_0126_png = 'packages/zombies/assets/dungeon/tile_0126.png';

  static const String assets_dungeon_tile_0127_png = 'assets/dungeon/tile_0127.png';
  static const String zombies$assets_dungeon_tile_0127_png = 'packages/zombies/assets/dungeon/tile_0127.png';

  static const String assets_dungeon_tile_0128_png = 'assets/dungeon/tile_0128.png';
  static const String zombies$assets_dungeon_tile_0128_png = 'packages/zombies/assets/dungeon/tile_0128.png';

  static const String assets_dungeon_tile_0129_png = 'assets/dungeon/tile_0129.png';
  static const String zombies$assets_dungeon_tile_0129_png = 'packages/zombies/assets/dungeon/tile_0129.png';

  static const String assets_dungeon_tile_0130_png = 'assets/dungeon/tile_0130.png';
  static const String zombies$assets_dungeon_tile_0130_png = 'packages/zombies/assets/dungeon/tile_0130.png';

  static const String assets_dungeon_tile_0131_png = 'assets/dungeon/tile_0131.png';
  static const String zombies$assets_dungeon_tile_0131_png = 'packages/zombies/assets/dungeon/tile_0131.png';

  static const String assets_dungeon_tilemap_png = 'assets/dungeon/tilemap.png';
  static const String zombies$assets_dungeon_tilemap_png = 'packages/zombies/assets/dungeon/tilemap.png';

  static const String assets_dungeon_tilemap_packed_png = 'assets/dungeon/tilemap_packed.png';
  static const String zombies$assets_dungeon_tilemap_packed_png = 'packages/zombies/assets/dungeon/tilemap_packed.png';

  static const String assets_tiles_world_tmx = 'assets/tiles/world.tmx';
  static const String zombies$assets_tiles_world_tmx = 'packages/zombies/assets/tiles/world.tmx';

  static const String assets_town_tile_0000_png = 'assets/town/tile_0000.png';
  static const String zombies$assets_town_tile_0000_png = 'packages/zombies/assets/town/tile_0000.png';

  static const String assets_town_tile_0001_png = 'assets/town/tile_0001.png';
  static const String zombies$assets_town_tile_0001_png = 'packages/zombies/assets/town/tile_0001.png';

  static const String assets_town_tile_0002_png = 'assets/town/tile_0002.png';
  static const String zombies$assets_town_tile_0002_png = 'packages/zombies/assets/town/tile_0002.png';

  static const String assets_town_tile_0003_png = 'assets/town/tile_0003.png';
  static const String zombies$assets_town_tile_0003_png = 'packages/zombies/assets/town/tile_0003.png';

  static const String assets_town_tile_0004_png = 'assets/town/tile_0004.png';
  static const String zombies$assets_town_tile_0004_png = 'packages/zombies/assets/town/tile_0004.png';

  static const String assets_town_tile_0005_png = 'assets/town/tile_0005.png';
  static const String zombies$assets_town_tile_0005_png = 'packages/zombies/assets/town/tile_0005.png';

  static const String assets_town_tile_0006_png = 'assets/town/tile_0006.png';
  static const String zombies$assets_town_tile_0006_png = 'packages/zombies/assets/town/tile_0006.png';

  static const String assets_town_tile_0007_png = 'assets/town/tile_0007.png';
  static const String zombies$assets_town_tile_0007_png = 'packages/zombies/assets/town/tile_0007.png';

  static const String assets_town_tile_0008_png = 'assets/town/tile_0008.png';
  static const String zombies$assets_town_tile_0008_png = 'packages/zombies/assets/town/tile_0008.png';

  static const String assets_town_tile_0009_png = 'assets/town/tile_0009.png';
  static const String zombies$assets_town_tile_0009_png = 'packages/zombies/assets/town/tile_0009.png';

  static const String assets_town_tile_0010_png = 'assets/town/tile_0010.png';
  static const String zombies$assets_town_tile_0010_png = 'packages/zombies/assets/town/tile_0010.png';

  static const String assets_town_tile_0011_png = 'assets/town/tile_0011.png';
  static const String zombies$assets_town_tile_0011_png = 'packages/zombies/assets/town/tile_0011.png';

  static const String assets_town_tile_0012_png = 'assets/town/tile_0012.png';
  static const String zombies$assets_town_tile_0012_png = 'packages/zombies/assets/town/tile_0012.png';

  static const String assets_town_tile_0013_png = 'assets/town/tile_0013.png';
  static const String zombies$assets_town_tile_0013_png = 'packages/zombies/assets/town/tile_0013.png';

  static const String assets_town_tile_0014_png = 'assets/town/tile_0014.png';
  static const String zombies$assets_town_tile_0014_png = 'packages/zombies/assets/town/tile_0014.png';

  static const String assets_town_tile_0015_png = 'assets/town/tile_0015.png';
  static const String zombies$assets_town_tile_0015_png = 'packages/zombies/assets/town/tile_0015.png';

  static const String assets_town_tile_0016_png = 'assets/town/tile_0016.png';
  static const String zombies$assets_town_tile_0016_png = 'packages/zombies/assets/town/tile_0016.png';

  static const String assets_town_tile_0017_png = 'assets/town/tile_0017.png';
  static const String zombies$assets_town_tile_0017_png = 'packages/zombies/assets/town/tile_0017.png';

  static const String assets_town_tile_0018_png = 'assets/town/tile_0018.png';
  static const String zombies$assets_town_tile_0018_png = 'packages/zombies/assets/town/tile_0018.png';

  static const String assets_town_tile_0019_png = 'assets/town/tile_0019.png';
  static const String zombies$assets_town_tile_0019_png = 'packages/zombies/assets/town/tile_0019.png';

  static const String assets_town_tile_0020_png = 'assets/town/tile_0020.png';
  static const String zombies$assets_town_tile_0020_png = 'packages/zombies/assets/town/tile_0020.png';

  static const String assets_town_tile_0021_png = 'assets/town/tile_0021.png';
  static const String zombies$assets_town_tile_0021_png = 'packages/zombies/assets/town/tile_0021.png';

  static const String assets_town_tile_0022_png = 'assets/town/tile_0022.png';
  static const String zombies$assets_town_tile_0022_png = 'packages/zombies/assets/town/tile_0022.png';

  static const String assets_town_tile_0023_png = 'assets/town/tile_0023.png';
  static const String zombies$assets_town_tile_0023_png = 'packages/zombies/assets/town/tile_0023.png';

  static const String assets_town_tile_0024_png = 'assets/town/tile_0024.png';
  static const String zombies$assets_town_tile_0024_png = 'packages/zombies/assets/town/tile_0024.png';

  static const String assets_town_tile_0025_png = 'assets/town/tile_0025.png';
  static const String zombies$assets_town_tile_0025_png = 'packages/zombies/assets/town/tile_0025.png';

  static const String assets_town_tile_0026_png = 'assets/town/tile_0026.png';
  static const String zombies$assets_town_tile_0026_png = 'packages/zombies/assets/town/tile_0026.png';

  static const String assets_town_tile_0027_png = 'assets/town/tile_0027.png';
  static const String zombies$assets_town_tile_0027_png = 'packages/zombies/assets/town/tile_0027.png';

  static const String assets_town_tile_0028_png = 'assets/town/tile_0028.png';
  static const String zombies$assets_town_tile_0028_png = 'packages/zombies/assets/town/tile_0028.png';

  static const String assets_town_tile_0029_png = 'assets/town/tile_0029.png';
  static const String zombies$assets_town_tile_0029_png = 'packages/zombies/assets/town/tile_0029.png';

  static const String assets_town_tile_0030_png = 'assets/town/tile_0030.png';
  static const String zombies$assets_town_tile_0030_png = 'packages/zombies/assets/town/tile_0030.png';

  static const String assets_town_tile_0031_png = 'assets/town/tile_0031.png';
  static const String zombies$assets_town_tile_0031_png = 'packages/zombies/assets/town/tile_0031.png';

  static const String assets_town_tile_0032_png = 'assets/town/tile_0032.png';
  static const String zombies$assets_town_tile_0032_png = 'packages/zombies/assets/town/tile_0032.png';

  static const String assets_town_tile_0033_png = 'assets/town/tile_0033.png';
  static const String zombies$assets_town_tile_0033_png = 'packages/zombies/assets/town/tile_0033.png';

  static const String assets_town_tile_0034_png = 'assets/town/tile_0034.png';
  static const String zombies$assets_town_tile_0034_png = 'packages/zombies/assets/town/tile_0034.png';

  static const String assets_town_tile_0035_png = 'assets/town/tile_0035.png';
  static const String zombies$assets_town_tile_0035_png = 'packages/zombies/assets/town/tile_0035.png';

  static const String assets_town_tile_0036_png = 'assets/town/tile_0036.png';
  static const String zombies$assets_town_tile_0036_png = 'packages/zombies/assets/town/tile_0036.png';

  static const String assets_town_tile_0037_png = 'assets/town/tile_0037.png';
  static const String zombies$assets_town_tile_0037_png = 'packages/zombies/assets/town/tile_0037.png';

  static const String assets_town_tile_0038_png = 'assets/town/tile_0038.png';
  static const String zombies$assets_town_tile_0038_png = 'packages/zombies/assets/town/tile_0038.png';

  static const String assets_town_tile_0039_png = 'assets/town/tile_0039.png';
  static const String zombies$assets_town_tile_0039_png = 'packages/zombies/assets/town/tile_0039.png';

  static const String assets_town_tile_0040_png = 'assets/town/tile_0040.png';
  static const String zombies$assets_town_tile_0040_png = 'packages/zombies/assets/town/tile_0040.png';

  static const String assets_town_tile_0041_png = 'assets/town/tile_0041.png';
  static const String zombies$assets_town_tile_0041_png = 'packages/zombies/assets/town/tile_0041.png';

  static const String assets_town_tile_0042_png = 'assets/town/tile_0042.png';
  static const String zombies$assets_town_tile_0042_png = 'packages/zombies/assets/town/tile_0042.png';

  static const String assets_town_tile_0043_png = 'assets/town/tile_0043.png';
  static const String zombies$assets_town_tile_0043_png = 'packages/zombies/assets/town/tile_0043.png';

  static const String assets_town_tile_0044_png = 'assets/town/tile_0044.png';
  static const String zombies$assets_town_tile_0044_png = 'packages/zombies/assets/town/tile_0044.png';

  static const String assets_town_tile_0045_png = 'assets/town/tile_0045.png';
  static const String zombies$assets_town_tile_0045_png = 'packages/zombies/assets/town/tile_0045.png';

  static const String assets_town_tile_0046_png = 'assets/town/tile_0046.png';
  static const String zombies$assets_town_tile_0046_png = 'packages/zombies/assets/town/tile_0046.png';

  static const String assets_town_tile_0047_png = 'assets/town/tile_0047.png';
  static const String zombies$assets_town_tile_0047_png = 'packages/zombies/assets/town/tile_0047.png';

  static const String assets_town_tile_0048_png = 'assets/town/tile_0048.png';
  static const String zombies$assets_town_tile_0048_png = 'packages/zombies/assets/town/tile_0048.png';

  static const String assets_town_tile_0049_png = 'assets/town/tile_0049.png';
  static const String zombies$assets_town_tile_0049_png = 'packages/zombies/assets/town/tile_0049.png';

  static const String assets_town_tile_0050_png = 'assets/town/tile_0050.png';
  static const String zombies$assets_town_tile_0050_png = 'packages/zombies/assets/town/tile_0050.png';

  static const String assets_town_tile_0051_png = 'assets/town/tile_0051.png';
  static const String zombies$assets_town_tile_0051_png = 'packages/zombies/assets/town/tile_0051.png';

  static const String assets_town_tile_0052_png = 'assets/town/tile_0052.png';
  static const String zombies$assets_town_tile_0052_png = 'packages/zombies/assets/town/tile_0052.png';

  static const String assets_town_tile_0053_png = 'assets/town/tile_0053.png';
  static const String zombies$assets_town_tile_0053_png = 'packages/zombies/assets/town/tile_0053.png';

  static const String assets_town_tile_0054_png = 'assets/town/tile_0054.png';
  static const String zombies$assets_town_tile_0054_png = 'packages/zombies/assets/town/tile_0054.png';

  static const String assets_town_tile_0055_png = 'assets/town/tile_0055.png';
  static const String zombies$assets_town_tile_0055_png = 'packages/zombies/assets/town/tile_0055.png';

  static const String assets_town_tile_0056_png = 'assets/town/tile_0056.png';
  static const String zombies$assets_town_tile_0056_png = 'packages/zombies/assets/town/tile_0056.png';

  static const String assets_town_tile_0057_png = 'assets/town/tile_0057.png';
  static const String zombies$assets_town_tile_0057_png = 'packages/zombies/assets/town/tile_0057.png';

  static const String assets_town_tile_0058_png = 'assets/town/tile_0058.png';
  static const String zombies$assets_town_tile_0058_png = 'packages/zombies/assets/town/tile_0058.png';

  static const String assets_town_tile_0059_png = 'assets/town/tile_0059.png';
  static const String zombies$assets_town_tile_0059_png = 'packages/zombies/assets/town/tile_0059.png';

  static const String assets_town_tile_0060_png = 'assets/town/tile_0060.png';
  static const String zombies$assets_town_tile_0060_png = 'packages/zombies/assets/town/tile_0060.png';

  static const String assets_town_tile_0061_png = 'assets/town/tile_0061.png';
  static const String zombies$assets_town_tile_0061_png = 'packages/zombies/assets/town/tile_0061.png';

  static const String assets_town_tile_0062_png = 'assets/town/tile_0062.png';
  static const String zombies$assets_town_tile_0062_png = 'packages/zombies/assets/town/tile_0062.png';

  static const String assets_town_tile_0063_png = 'assets/town/tile_0063.png';
  static const String zombies$assets_town_tile_0063_png = 'packages/zombies/assets/town/tile_0063.png';

  static const String assets_town_tile_0064_png = 'assets/town/tile_0064.png';
  static const String zombies$assets_town_tile_0064_png = 'packages/zombies/assets/town/tile_0064.png';

  static const String assets_town_tile_0065_png = 'assets/town/tile_0065.png';
  static const String zombies$assets_town_tile_0065_png = 'packages/zombies/assets/town/tile_0065.png';

  static const String assets_town_tile_0066_png = 'assets/town/tile_0066.png';
  static const String zombies$assets_town_tile_0066_png = 'packages/zombies/assets/town/tile_0066.png';

  static const String assets_town_tile_0067_png = 'assets/town/tile_0067.png';
  static const String zombies$assets_town_tile_0067_png = 'packages/zombies/assets/town/tile_0067.png';

  static const String assets_town_tile_0068_png = 'assets/town/tile_0068.png';
  static const String zombies$assets_town_tile_0068_png = 'packages/zombies/assets/town/tile_0068.png';

  static const String assets_town_tile_0069_png = 'assets/town/tile_0069.png';
  static const String zombies$assets_town_tile_0069_png = 'packages/zombies/assets/town/tile_0069.png';

  static const String assets_town_tile_0070_png = 'assets/town/tile_0070.png';
  static const String zombies$assets_town_tile_0070_png = 'packages/zombies/assets/town/tile_0070.png';

  static const String assets_town_tile_0071_png = 'assets/town/tile_0071.png';
  static const String zombies$assets_town_tile_0071_png = 'packages/zombies/assets/town/tile_0071.png';

  static const String assets_town_tile_0072_png = 'assets/town/tile_0072.png';
  static const String zombies$assets_town_tile_0072_png = 'packages/zombies/assets/town/tile_0072.png';

  static const String assets_town_tile_0073_png = 'assets/town/tile_0073.png';
  static const String zombies$assets_town_tile_0073_png = 'packages/zombies/assets/town/tile_0073.png';

  static const String assets_town_tile_0074_png = 'assets/town/tile_0074.png';
  static const String zombies$assets_town_tile_0074_png = 'packages/zombies/assets/town/tile_0074.png';

  static const String assets_town_tile_0075_png = 'assets/town/tile_0075.png';
  static const String zombies$assets_town_tile_0075_png = 'packages/zombies/assets/town/tile_0075.png';

  static const String assets_town_tile_0076_png = 'assets/town/tile_0076.png';
  static const String zombies$assets_town_tile_0076_png = 'packages/zombies/assets/town/tile_0076.png';

  static const String assets_town_tile_0077_png = 'assets/town/tile_0077.png';
  static const String zombies$assets_town_tile_0077_png = 'packages/zombies/assets/town/tile_0077.png';

  static const String assets_town_tile_0078_png = 'assets/town/tile_0078.png';
  static const String zombies$assets_town_tile_0078_png = 'packages/zombies/assets/town/tile_0078.png';

  static const String assets_town_tile_0079_png = 'assets/town/tile_0079.png';
  static const String zombies$assets_town_tile_0079_png = 'packages/zombies/assets/town/tile_0079.png';

  static const String assets_town_tile_0080_png = 'assets/town/tile_0080.png';
  static const String zombies$assets_town_tile_0080_png = 'packages/zombies/assets/town/tile_0080.png';

  static const String assets_town_tile_0081_png = 'assets/town/tile_0081.png';
  static const String zombies$assets_town_tile_0081_png = 'packages/zombies/assets/town/tile_0081.png';

  static const String assets_town_tile_0082_png = 'assets/town/tile_0082.png';
  static const String zombies$assets_town_tile_0082_png = 'packages/zombies/assets/town/tile_0082.png';

  static const String assets_town_tile_0083_png = 'assets/town/tile_0083.png';
  static const String zombies$assets_town_tile_0083_png = 'packages/zombies/assets/town/tile_0083.png';

  static const String assets_town_tile_0084_png = 'assets/town/tile_0084.png';
  static const String zombies$assets_town_tile_0084_png = 'packages/zombies/assets/town/tile_0084.png';

  static const String assets_town_tile_0085_png = 'assets/town/tile_0085.png';
  static const String zombies$assets_town_tile_0085_png = 'packages/zombies/assets/town/tile_0085.png';

  static const String assets_town_tile_0086_png = 'assets/town/tile_0086.png';
  static const String zombies$assets_town_tile_0086_png = 'packages/zombies/assets/town/tile_0086.png';

  static const String assets_town_tile_0087_png = 'assets/town/tile_0087.png';
  static const String zombies$assets_town_tile_0087_png = 'packages/zombies/assets/town/tile_0087.png';

  static const String assets_town_tile_0088_png = 'assets/town/tile_0088.png';
  static const String zombies$assets_town_tile_0088_png = 'packages/zombies/assets/town/tile_0088.png';

  static const String assets_town_tile_0089_png = 'assets/town/tile_0089.png';
  static const String zombies$assets_town_tile_0089_png = 'packages/zombies/assets/town/tile_0089.png';

  static const String assets_town_tile_0090_png = 'assets/town/tile_0090.png';
  static const String zombies$assets_town_tile_0090_png = 'packages/zombies/assets/town/tile_0090.png';

  static const String assets_town_tile_0091_png = 'assets/town/tile_0091.png';
  static const String zombies$assets_town_tile_0091_png = 'packages/zombies/assets/town/tile_0091.png';

  static const String assets_town_tile_0092_png = 'assets/town/tile_0092.png';
  static const String zombies$assets_town_tile_0092_png = 'packages/zombies/assets/town/tile_0092.png';

  static const String assets_town_tile_0093_png = 'assets/town/tile_0093.png';
  static const String zombies$assets_town_tile_0093_png = 'packages/zombies/assets/town/tile_0093.png';

  static const String assets_town_tile_0094_png = 'assets/town/tile_0094.png';
  static const String zombies$assets_town_tile_0094_png = 'packages/zombies/assets/town/tile_0094.png';

  static const String assets_town_tile_0095_png = 'assets/town/tile_0095.png';
  static const String zombies$assets_town_tile_0095_png = 'packages/zombies/assets/town/tile_0095.png';

  static const String assets_town_tile_0096_png = 'assets/town/tile_0096.png';
  static const String zombies$assets_town_tile_0096_png = 'packages/zombies/assets/town/tile_0096.png';

  static const String assets_town_tile_0097_png = 'assets/town/tile_0097.png';
  static const String zombies$assets_town_tile_0097_png = 'packages/zombies/assets/town/tile_0097.png';

  static const String assets_town_tile_0098_png = 'assets/town/tile_0098.png';
  static const String zombies$assets_town_tile_0098_png = 'packages/zombies/assets/town/tile_0098.png';

  static const String assets_town_tile_0099_png = 'assets/town/tile_0099.png';
  static const String zombies$assets_town_tile_0099_png = 'packages/zombies/assets/town/tile_0099.png';

  static const String assets_town_tile_0100_png = 'assets/town/tile_0100.png';
  static const String zombies$assets_town_tile_0100_png = 'packages/zombies/assets/town/tile_0100.png';

  static const String assets_town_tile_0101_png = 'assets/town/tile_0101.png';
  static const String zombies$assets_town_tile_0101_png = 'packages/zombies/assets/town/tile_0101.png';

  static const String assets_town_tile_0102_png = 'assets/town/tile_0102.png';
  static const String zombies$assets_town_tile_0102_png = 'packages/zombies/assets/town/tile_0102.png';

  static const String assets_town_tile_0103_png = 'assets/town/tile_0103.png';
  static const String zombies$assets_town_tile_0103_png = 'packages/zombies/assets/town/tile_0103.png';

  static const String assets_town_tile_0104_png = 'assets/town/tile_0104.png';
  static const String zombies$assets_town_tile_0104_png = 'packages/zombies/assets/town/tile_0104.png';

  static const String assets_town_tile_0105_png = 'assets/town/tile_0105.png';
  static const String zombies$assets_town_tile_0105_png = 'packages/zombies/assets/town/tile_0105.png';

  static const String assets_town_tile_0106_png = 'assets/town/tile_0106.png';
  static const String zombies$assets_town_tile_0106_png = 'packages/zombies/assets/town/tile_0106.png';

  static const String assets_town_tile_0107_png = 'assets/town/tile_0107.png';
  static const String zombies$assets_town_tile_0107_png = 'packages/zombies/assets/town/tile_0107.png';

  static const String assets_town_tile_0108_png = 'assets/town/tile_0108.png';
  static const String zombies$assets_town_tile_0108_png = 'packages/zombies/assets/town/tile_0108.png';

  static const String assets_town_tile_0109_png = 'assets/town/tile_0109.png';
  static const String zombies$assets_town_tile_0109_png = 'packages/zombies/assets/town/tile_0109.png';

  static const String assets_town_tile_0110_png = 'assets/town/tile_0110.png';
  static const String zombies$assets_town_tile_0110_png = 'packages/zombies/assets/town/tile_0110.png';

  static const String assets_town_tile_0111_png = 'assets/town/tile_0111.png';
  static const String zombies$assets_town_tile_0111_png = 'packages/zombies/assets/town/tile_0111.png';

  static const String assets_town_tile_0112_png = 'assets/town/tile_0112.png';
  static const String zombies$assets_town_tile_0112_png = 'packages/zombies/assets/town/tile_0112.png';

  static const String assets_town_tile_0113_png = 'assets/town/tile_0113.png';
  static const String zombies$assets_town_tile_0113_png = 'packages/zombies/assets/town/tile_0113.png';

  static const String assets_town_tile_0114_png = 'assets/town/tile_0114.png';
  static const String zombies$assets_town_tile_0114_png = 'packages/zombies/assets/town/tile_0114.png';

  static const String assets_town_tile_0115_png = 'assets/town/tile_0115.png';
  static const String zombies$assets_town_tile_0115_png = 'packages/zombies/assets/town/tile_0115.png';

  static const String assets_town_tile_0116_png = 'assets/town/tile_0116.png';
  static const String zombies$assets_town_tile_0116_png = 'packages/zombies/assets/town/tile_0116.png';

  static const String assets_town_tile_0117_png = 'assets/town/tile_0117.png';
  static const String zombies$assets_town_tile_0117_png = 'packages/zombies/assets/town/tile_0117.png';

  static const String assets_town_tile_0118_png = 'assets/town/tile_0118.png';
  static const String zombies$assets_town_tile_0118_png = 'packages/zombies/assets/town/tile_0118.png';

  static const String assets_town_tile_0119_png = 'assets/town/tile_0119.png';
  static const String zombies$assets_town_tile_0119_png = 'packages/zombies/assets/town/tile_0119.png';

  static const String assets_town_tile_0120_png = 'assets/town/tile_0120.png';
  static const String zombies$assets_town_tile_0120_png = 'packages/zombies/assets/town/tile_0120.png';

  static const String assets_town_tile_0121_png = 'assets/town/tile_0121.png';
  static const String zombies$assets_town_tile_0121_png = 'packages/zombies/assets/town/tile_0121.png';

  static const String assets_town_tile_0122_png = 'assets/town/tile_0122.png';
  static const String zombies$assets_town_tile_0122_png = 'packages/zombies/assets/town/tile_0122.png';

  static const String assets_town_tile_0123_png = 'assets/town/tile_0123.png';
  static const String zombies$assets_town_tile_0123_png = 'packages/zombies/assets/town/tile_0123.png';

  static const String assets_town_tile_0124_png = 'assets/town/tile_0124.png';
  static const String zombies$assets_town_tile_0124_png = 'packages/zombies/assets/town/tile_0124.png';

  static const String assets_town_tile_0125_png = 'assets/town/tile_0125.png';
  static const String zombies$assets_town_tile_0125_png = 'packages/zombies/assets/town/tile_0125.png';

  static const String assets_town_tile_0126_png = 'assets/town/tile_0126.png';
  static const String zombies$assets_town_tile_0126_png = 'packages/zombies/assets/town/tile_0126.png';

  static const String assets_town_tile_0127_png = 'assets/town/tile_0127.png';
  static const String zombies$assets_town_tile_0127_png = 'packages/zombies/assets/town/tile_0127.png';

  static const String assets_town_tile_0128_png = 'assets/town/tile_0128.png';
  static const String zombies$assets_town_tile_0128_png = 'packages/zombies/assets/town/tile_0128.png';

  static const String assets_town_tile_0129_png = 'assets/town/tile_0129.png';
  static const String zombies$assets_town_tile_0129_png = 'packages/zombies/assets/town/tile_0129.png';

  static const String assets_town_tile_0130_png = 'assets/town/tile_0130.png';
  static const String zombies$assets_town_tile_0130_png = 'packages/zombies/assets/town/tile_0130.png';

  static const String assets_town_tile_0131_png = 'assets/town/tile_0131.png';
  static const String zombies$assets_town_tile_0131_png = 'packages/zombies/assets/town/tile_0131.png';

  static const String assets_town_tilemap_png = 'assets/town/tilemap.png';
  static const String zombies$assets_town_tilemap_png = 'packages/zombies/assets/town/tilemap.png';

  static const String assets_town_tilemap_packed_png = 'assets/town/tilemap_packed.png';
  static const String zombies$assets_town_tilemap_packed_png = 'packages/zombies/assets/town/tilemap_packed.png';

  static const String assets_town_town_tsx = 'assets/town/town.tsx';
  static const String zombies$assets_town_town_tsx = 'packages/zombies/assets/town/town.tsx';
}
